version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www
    ports: 
      - '3000:3000'
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/var/www
    command: ["npm", "run", "test"]